services:
  app:
    container_name: app
    build:
      target: development
      context: .
    environment:
      REDIS_URL: redis://redis:6379/0
      BROWSER_URL: ws://chromium:3000?token=local
    volumes:
      - ./:/app
    depends_on:
      redis:
        condition: service_healthy
      chromium:
        condition: service_healthy

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - redis-data:/data

  chromium:
    container_name: chromium
    image: ghcr.io/browserless/chromium
    environment:
      TOKEN: local
      HOST: chromium
      DEBUG: -*
    healthcheck:
      test: ["CMD", "curl", "localhost:3000/active?token=local"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  redis-data:
