name: scrobble-deduplicator
services:
  app:
    container_name: app
    image: ghcr.io/cterence/scrobble-deduplicator:latest@sha256:5e7ff7acc77fc2fa6bea870480af617c1f608828ff6bafc0461fe0cf2fc36934
    environment:
      REDIS_URL: redis://redis:6379/0
      BROWSER_URL: ws://chromium:3000?token=local
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./data:/app/data:rw
    depends_on:
      redis:
        condition: service_healthy
      chromium:
        condition: service_healthy

  redis:
    container_name: redis
    image: redis:latest@sha256:25dbb04fc4d6d190eda327dab551631500b0f9ac8f9808e8e63b7fda1ddff196
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  chromium:
    container_name: chromium
    image: ghcr.io/browserless/chromium:latest@sha256:5fc8077ceb90499f920f0896a2f50a1cb95305fa128b7099821e11f0a35fac2c
    environment:
      TOKEN: local
      DEBUG: -*
      TIMEOUT: 600000
    healthcheck:
      test: ["CMD", "curl", "http://localhost:3000/active?token=local"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  redis-data:
