name: dev
services:
  app:
    container_name: app-dev
    build:
      target: development
      context: .
    environment:
      REDIS_URL: redis://redis:6379/0
      BROWSER_URL: ws://chromium-dev:3000?token=local
    volumes:
      - ./:/app
    depends_on:
      redis:
        condition: service_healthy
      chromium:
        condition: service_healthy

  redis:
    container_name: redis-dev
    image: redis:latest@sha256:f0957bcaa75fd58a9a1847c1f07caf370579196259d69ac07f2e27b5b389b021
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - redis-data:/data

  chromium:
    container_name: chromium-dev
    image: ghcr.io/browserless/chromium:latest@sha256:e0d0a570f68afb0d0f7a442a1938cc356832c43a484445d9eec15dceba0b5427
    ports:
      - 3000:3000
    environment:
      TOKEN: local
      TIMEOUT: 600000
      HOST: chromium-dev
      DEBUG: -*
    healthcheck:
      test: ["CMD", "curl", "http://chromium-dev:3000/active?token=local"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  redis-data:
