name: scrobble-deduplicator
services:
  app:
    container_name: app
    image: ghcr.io/cterence/scrobble-deduplicator:latest@sha256:5e7ff7acc77fc2fa6bea870480af617c1f608828ff6bafc0461fe0cf2fc36934
    environment:
      REDIS_URL: redis://redis:6379/0
      BROWSER_URL: ws://chromium:3000?token=local
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./data:/app/data:rw
    depends_on:
      redis:
        condition: service_healthy
      chromium:
        condition: service_healthy

  redis:
    container_name: redis
    image: redis:latest@sha256:832d7785830f3f4b559300e6191fc914b15642c1935252338825cf4332200148
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  chromium:
    container_name: chromium
    image: ghcr.io/browserless/chromium:latest@sha256:813077a39aa815e165503fb38edf917408dd885b9b3a1d8bc4f2e013bcfd38a7
    environment:
      TOKEN: local
      DEBUG: -*
      TIMEOUT: 600000
    healthcheck:
      test: ["CMD", "curl", "http://localhost:3000/active?token=local"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  redis-data:
