cacheType: inmemory # redis|file|inmemory
lastfm:
  username: musiclover
  password: secret!
from: 01-01-2025
to: 01-03-2025
browserHeadful: false
redisURL: "" # redis://localhost:6379/0
logLevel: info
delete: false
browserURL: "" # ws://localhost:3000?token=local
