cacheType: inmemory # redis|file|inmemory
lastfm:
  username: musiclover
  password: secret!
from: 01-01-2025
to: 01-03-2025
# startPage: 3 # Incompatible with from/to arguments
browserHeadful: false
redisURL: "" # redis://localhost:6379/0
logLevel: info
canDelete: false
browserURL: "" # ws://localhost:3000?token=local
dataDir: ./data
telegramBotToken: ""
telegramChatID: ""
